name: training-pipeline-on-push

on:
  push:
    branches:
      - master
  

jobs:

  training_pipeline:

    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI:"http://127.0.0.1:5000"

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip3 install -U pip && pip3 install -r requirements.txt

    - name: Executing training pipeline
      run: python pipelines/training.py --environment=pypi run