name: training-pipeline-on-push

on:
  push:
    branches:
      - master
  

jobs:

  training_pipeline:

    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{secrets.MLFLOW_URI}}
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip3 install -U pip && pip3 install -r requirements.txt

    # - name: Set MLflow Tracking URI
    #   run: echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_URI }}" >> .env
    
    # - name: Start MLflow Server (background)
    #   run: mlflow server --host ${{secrets.ADDRESS}} --port 5000

    - name: Executing training pipeline
      run: python pipelines/training.py --environment=pypi run

    # - name: Await MLflow Server Shutdown
    #   if: always()  # Run even if previous steps fail
    #   run: pkill -f "mlflow server" || true # Stop the server gracefully